package com.aldogrand.kfc.msg.events.integration;

public enum CommandType {
    LOGIN_COMMAND,
    FETCH_EVENTS_COMMAND, 
    FETCH_EVENT_COMMAND, 
    FETCH_MARKETS_COMMAND, 
    FETCH_MARKET_COMMAND, 
    FETCH_RUNNERS_COMMAND, 
    FETCH_RUNNER_COMMAND, 
    FETCH_PRICES_COMMAND, 
    FETCH_POSITIONS_COMMAND, 
    FETCH_OFFER_COMMAND, 
    FETCH_OFFERS_COMMAND,
    CANCEL_OFFER_COMMAND,
    CANCEL_OFFERS_COMMAND,
    SUBMIT_OFFER_COMMAND,
    SUBMIT_OFFERS_COMMAND
}
