package com.aldogrand.sbpc.model;

public enum EventStatus {
	OPEN, 
	PRE_EVENT_LIVE,
	CLOSED,
	SUSPENDED,
	FIRST_HALF,
	HALF_TIME,
	SECOND_HALF,
	BEFORE_EXTRA_TIME,
	EXTRA_TIME_FIRST_HALF,
	EXTRA_TIME_HALF_TIME,
	EXTRA_TIME_SECOND_HALF,
	BEFORE_PENALTY_SHOOTOUT,
	PENALTY_SHOOTOUT,
	UNKNOWN;
}
